version: '3'

includes:
  default: https://raw.githubusercontent.com/hoomy-official/taskfile-default/main/tasks.yaml
  markdownlint: https://raw.githubusercontent.com/hoomy-official/taskfile-markdownlint/main/tasks.yaml
  git: ./tasks.yaml

dotenv:
  - .env
  - .env.default